# Chapter 9: Blobs, Image, Digits, Moons & Generated

This notebook contains the code for chapter 9 of the Hands-on Machine Learning with Scikit-Learn, Keras & Tensorflow book.

In [1]:
from sklearn.mixture import BayesianGaussianMixture, GaussianMixture
from sklearn.datasets import load_digits, make_blobs, make_moons
from sklearn.cluster import DBSCAN, KMeans, MiniBatchKMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

from matplotlib.image import imread
import numpy as np

## Global configuration

In [2]:
ASSETS_PATH = "./assets/"

RANDOM_SEED = 42

JOB_COUNT = 3

In [3]:
np.random.seed(RANDOM_SEED)

## Load <ins>blobs</ins> data 

In [4]:
centers = np.array([[ 0.2,  2.3],[-1.5 ,  2.3],[-2.8,  1.8],[-2.8,  2.8],[-2.8,  1.3]])
stdevs = np.array([0.4, 0.3, 0.1, 0.1, 0.1])

In [5]:
X, y = make_blobs(n_samples=2000, centers=centers, cluster_std=stdevs, random_state=RANDOM_SEED)

## Train <ins>k-means</ins> model

In [6]:
km_model = KMeans(n_clusters=5)

In [7]:
%%time
y_predictions = km_model.fit_predict(X)
y_predictions

CPU times: user 212 ms, sys: 41.4 ms, total: 254 ms
Wall time: 35.9 ms


array([3, 0, 2, ..., 0, 3, 1], dtype=int32)

In [8]:
km_model.cluster_centers_

array([[ 0.20925539,  2.30351618],
       [-2.80372723,  1.80873739],
       [-1.4453407 ,  2.32051326],
       [-2.79846237,  2.80004584],
       [-2.79244799,  1.2973862 ]])

## Evaluate <ins>k-means</ins> model

In [9]:
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])

In [10]:
km_model.predict(X_new)

array([0, 0, 3, 3], dtype=int32)

In [11]:
km_model.transform(X_new)

array([[0.36865958, 2.81024337, 1.48045212, 2.91057812, 2.87948466],
       [2.80720102, 5.80687792, 4.45688037, 5.85339553, 5.8349053 ],
       [3.28396253, 1.20732332, 1.69666372, 0.28389977, 1.71521765],
       [3.21526454, 0.7185868 , 1.56498595, 0.36144837, 1.22039247]])

## Train <ins>k-means</ins> model (manual init)

In [12]:
centers = np.array([[-3, 3], [-3, 2], [-3, 1], [-1, 2], [0, 2]])

In [13]:
km_model = KMeans(n_clusters=5, init=centers, n_init=1)

In [14]:
%%time
km_model.fit(X)

CPU times: user 6.82 ms, sys: 4.62 ms, total: 11.4 ms
Wall time: 2.69 ms


KMeans(init=array([[-3,  3],
       [-3,  2],
       [-3,  1],
       [-1,  2],
       [ 0,  2]]),
       n_clusters=5, n_init=1)

In [15]:
km_model.cluster_centers_

array([[-2.79846237,  2.80004584],
       [-2.80372723,  1.80873739],
       [-2.79244799,  1.2973862 ],
       [-1.4453407 ,  2.32051326],
       [ 0.20925539,  2.30351618]])

In [16]:
km_model.inertia_

213.42177131258921

## Train <ins>k-means</ins> model (minibatches)

In [17]:
mbkm_model = MiniBatchKMeans(n_clusters=5)

In [18]:
%%time
mbkm_model.fit(X)

CPU times: user 28.5 ms, sys: 8.29 ms, total: 36.8 ms
Wall time: 26 ms


MiniBatchKMeans(n_clusters=5)

In [19]:
mbkm_model.cluster_centers_

array([[ 0.22270594,  2.32635029],
       [-2.79937075,  1.53940327],
       [-2.80763649,  2.80702889],
       [-1.30478636,  2.0684536 ],
       [-1.55943359,  2.55142098]])

In [20]:
mbkm_model.inertia_

241.2791397398836

## Load <ins>image</ins> data

In [21]:
image = imread(ASSETS_PATH + "ladybug.png")

In [22]:
image.shape

(533, 800, 3)

## Transform <ins>image</ins> data

In [23]:
X = image.reshape(-1, 3)

## Train <ins>k-means</ins> model

In [24]:
km_model = KMeans(n_clusters=8)

In [25]:
%%time
km_model.fit(X)

CPU times: user 46.3 s, sys: 164 ms, total: 46.5 s
Wall time: 4.43 s


KMeans()

In [26]:
segmented_image = km_model.cluster_centers_[km_model.labels_]
segmented_image.reshape(image.shape)

array([[[0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        ...,
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415]],

       [[0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        ...,
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415]],

       [[0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        ...,
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415],
        [0.21325621, 0.3807997 , 0.05521415]],

       ...,

       [[0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0.10831228, 0.00568088],
        [0.02201903, 0

## Load <ins>digits</ins> data

In [27]:
X, y = load_digits(return_X_y=True)

## Split <ins>digits</ins> data

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Train <ins>logistic regression</ins> model

In [29]:
lr_model = LogisticRegression(random_state=RANDOM_SEED)

In [30]:
%%time
lr_model.fit(X_train, y_train)

CPU times: user 467 ms, sys: 1.9 s, total: 2.37 s
Wall time: 156 ms


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

## Performance <ins>logistic regression</ins> model

In [31]:
lr_model.score(X_test, y_test)

0.9666666666666667

## Train <ins>k-means + logistic regression</ins> model

In [32]:
pipeline = Pipeline([
    ("kmeans", KMeans(n_clusters=50)),
    ("logistic_regression", LogisticRegression(random_state=RANDOM_SEED)),
])

In [33]:
%%time
pipeline.fit(X_train, y_train)

CPU times: user 8.92 s, sys: 17.9 s, total: 26.8 s
Wall time: 1.77 s


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Pipeline(steps=[('kmeans', KMeans(n_clusters=50)),
                ('logistic_regression', LogisticRegression(random_state=42))])

## Performance <ins>k-means + logistic regression</ins> model

In [34]:
pipeline.score(X_test, y_test)

0.9644444444444444

## Tune <ins>k-means + logistic regression</ins> model

In [35]:
parameters = {
    "kmeans__n_clusters": range(2, 100),
}

In [36]:
grid_search = GridSearchCV(pipeline, parameters, cv=3, n_jobs=JOB_COUNT)

In [37]:
%%time
grid_search.fit(X_train, y_train)

CPU times: user 11.2 s, sys: 22.5 s, total: 33.7 s
Wall time: 4min 26s


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('kmeans', KMeans(n_clusters=50)),
                                       ('logistic_regression',
                                        LogisticRegression(random_state=42))]),
             n_jobs=3, param_grid={'kmeans__n_clusters': range(2, 100)})

In [38]:
grid_search.best_params_

{'kmeans__n_clusters': 52}

In [39]:
grid_search.best_estimator_

Pipeline(steps=[('kmeans', KMeans(n_clusters=52)),
                ('logistic_regression', LogisticRegression(random_state=42))])

## Performance <ins>k-means + logistic regression</ins> model

In [40]:
grid_search.score(X_test, y_test)

0.9577777777777777

## Train <ins>logistic regression</ins> model

In [41]:
n_labeled = 50

In [42]:
lr_model = LogisticRegression()

In [43]:
%%time
lr_model.fit(X_train[:n_labeled], y_train[:n_labeled])

CPU times: user 207 ms, sys: 628 ms, total: 835 ms
Wall time: 87.4 ms


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Performance <ins>logistic regression</ins> model

In [44]:
lr_model.score(X_test, y_test)

0.8644444444444445

## Cluster <ins>digits</ins> data

In [45]:
km_model = KMeans(n_clusters=50)

In [46]:
%%time
X_train_distances = km_model.fit_transform(X_train)

CPU times: user 9.7 s, sys: 17.6 s, total: 27.3 s
Wall time: 2.13 s


In [47]:
representative_idx = np.argmin(X_train_distances, axis=0)

X_train_representative = X_train[representative_idx]
y_train_representative = y_train[representative_idx] # HACK: not available (label digits manually)

## Train <ins>logistic regression</ins> model

In [48]:
lr_model = LogisticRegression()

In [49]:
%%time
lr_model.fit(X_train_representative, y_train_representative)

CPU times: user 147 ms, sys: 568 ms, total: 715 ms
Wall time: 57.2 ms


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Performance <ins>logistic regression</ins> model

In [50]:
lr_model.score(X_test, y_test)

0.92

## Propagate <ins>digits</ins> data

In [51]:
y_train_propagated = np.empty(len(X_train), dtype=np.int32)

In [52]:
for idx in range(50):
    y_train_propagated[km_model.labels_ == idx] = y_train_representative[idx]

## Train <ins>logistic regression</ins> model

In [53]:
lr_model = LogisticRegression()

In [54]:
%%time
lr_model.fit(X_train, y_train_propagated)

CPU times: user 966 ms, sys: 3.02 s, total: 3.98 s
Wall time: 314 ms


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Performance <ins>logistic regression</ins> model

In [55]:
lr_model.score(X_test, y_test)

0.94

## Partially propagate <ins>digits</ins> data

In [56]:
X_train_cluster_distances = X_train_distances[np.arange(len(X_train)), km_model.labels_]

In [57]:
for idx in range(50):
    in_cluster = (km_model.labels_ == idx)
    
    cluster_distance = X_train_cluster_distances[in_cluster]
    
    cutoff_distance = np.percentile(cluster_distance, 75)
    is_above_cutoff = (X_train_cluster_distances > cutoff_distance)
    
    X_train_cluster_distances[in_cluster & is_above_cutoff] = -1
    
partially_propagated = (X_train_cluster_distances != -1)

X_train_partially_propagated = X_train[partially_propagated]
y_train_partially_propagated = y_train_propagated[partially_propagated]

## Train <ins>logistic regression</ins> model

In [58]:
lr_model = LogisticRegression()

In [59]:
%%time
lr_model.fit(X_train_partially_propagated, y_train_partially_propagated)

CPU times: user 1.14 s, sys: 4.79 s, total: 5.93 s
Wall time: 466 ms


/home/tomdewildt/Projects/introduction-to-machine-learning/venv/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Performance <ins>logistic regression</ins> model

In [60]:
lr_model.score(X_test, y_test)

0.9333333333333333

## Load <ins>moons</ins> data

In [61]:
X, y = make_moons(n_samples=1000, noise=0.05)

## Train <ins>dbscan</ins> model

In [62]:
dbs_model = DBSCAN(eps=0.05, min_samples=5)

In [63]:
%%time
dbs_model.fit(X)

CPU times: user 16.4 ms, sys: 109 ms, total: 126 ms
Wall time: 9.77 ms


DBSCAN(eps=0.05)

In [64]:
dbs_model.components_

array([[-1.00030833,  0.23019702],
       [ 0.65674362, -0.41152695],
       [ 0.27589495,  0.9386766 ],
       ...,
       [ 0.43383351, -0.38401021],
       [ 1.74015212, -0.14947994],
       [ 0.65779155,  0.83125706]])

In [65]:
dbs_model.labels_

array([ 7,  0,  1,  1,  2, -1, -1,  0,  2, -1,  2,  2,  2,  1,  1,  1,  2,
        0,  3,  2,  3,  1,  2,  2,  2, -1,  1,  4,  1,  2, -1,  0,  5,  1,
        2,  1,  1,  0,  4,  2,  3,  2,  1,  2,  0,  2,  2,  1, -1,  1,  2,
        1,  2,  1,  1, -1,  2,  1,  2,  1,  3,  2,  1,  1,  2,  3,  5,  2,
        1,  6,  2,  2,  2,  1,  0,  1,  2,  6,  3,  3,  1,  1,  2,  3,  3,
        1,  2,  3,  1,  3,  4,  1,  1,  2,  1,  0,  2,  3,  0,  2,  6,  2,
        2,  1,  3,  2,  3,  1,  3,  4,  2,  7,  1,  2,  0,  0,  4,  2,  3,
        0,  1, -1,  1,  3,  1,  1,  2,  2, -1,  4,  0,  0,  2,  1, -1,  2,
        1,  2,  6,  1, -1,  2,  5,  1,  5, -1,  3, -1,  3,  2,  1,  0,  1,
        3,  3, -1,  1,  1,  2,  0,  1,  6,  0,  1,  1,  1,  1,  3,  4, -1,
        2,  2,  7,  1,  1,  1,  3,  0,  1,  1,  5,  6, -1,  0,  4,  0,  4,
        1,  2,  3,  0,  2,  3, -1,  3,  1, -1,  1,  2,  2,  1,  1,  0,  1,
        3,  1,  3,  0,  2,  1,  3,  1,  0,  2,  0,  1,  1,  0,  4,  1,  2,
        1,  1,  3,  7,  1

In [66]:
dbs_model.core_sample_indices_

array([  1,   3,   4,   7,   8,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  26,  27,  28,  29,  31,  32,
        33,  37,  39,  40,  41,  42,  44,  45,  46,  47,  49,  50,  52,
        53,  54,  56,  57,  58,  59,  60,  62,  63,  64,  65,  67,  68,
        69,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 122, 123, 124,
       125, 126, 127, 129, 131, 132, 133, 136, 137, 138, 139, 141, 142,
       143, 144, 146, 148, 150, 151, 152, 153, 154, 156, 158, 159, 160,
       162, 163, 164, 165, 166, 167, 168, 170, 171, 172, 175, 176, 177,
       178, 179, 180, 181, 184, 186, 187, 188, 190, 191, 192, 194, 197,
       200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 212, 213,
       214, 216, 217, 218, 219, 220, 221, 222, 223, 226, 227, 22

## Train <ins>k-nearest neighbors</ins> model

In [67]:
knn_model = KNeighborsClassifier(n_neighbors=50)

In [68]:
%%time
knn_model.fit(dbs_model.components_, dbs_model.labels_[dbs_model.core_sample_indices_])

CPU times: user 3.49 ms, sys: 3.26 ms, total: 6.75 ms
Wall time: 1.26 ms


KNeighborsClassifier(n_neighbors=50)

## Evaluate <ins>k-nearest neighbors</ins> model

In [69]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

In [70]:
knn_model.predict(X_new)

array([0, 1, 1, 3])

In [71]:
knn_model.predict_proba(X_new)

array([[0.88, 0.1 , 0.  , 0.  , 0.  , 0.02, 0.  , 0.  ],
       [0.  , 0.56, 0.  , 0.  , 0.  , 0.44, 0.  , 0.  ],
       [0.  , 0.42, 0.18, 0.  , 0.  , 0.  , 0.  , 0.4 ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ]])

## Generate data

In [72]:
X1, y1 = make_blobs(n_samples=1000, centers=((4, -4), (0, 0)), random_state=RANDOM_SEED)
X1 = X1.dot(np.array([[0.374, 0.95], [0.732, 0.598]]))

In [73]:
X2, y2 = make_blobs(n_samples=250, centers=1, random_state=RANDOM_SEED)
X2 = X2 + [6, -8]

In [74]:
X = np.r_[X1, X2]
y = np.r_[y1, y2]

## Train <ins>gaussian mixture</ins> model

In [75]:
gm_model = GaussianMixture(n_components=3, n_init=10)

In [76]:
%%time
gm_model.fit(X)

CPU times: user 1.2 s, sys: 1.01 s, total: 2.22 s
Wall time: 237 ms


GaussianMixture(n_components=3, n_init=10)

In [77]:
gm_model.weights_

array([0.3902064 , 0.20970929, 0.40008431])

In [78]:
gm_model.means_

array([[ 0.0512132 ,  0.07512971],
       [ 3.39854326,  1.05926051],
       [-1.4076241 ,  1.42704927]])

In [79]:
gm_model.covariances_

array([[[ 0.68780591,  0.79597839],
        [ 0.79597839,  1.21232694]],

       [[ 1.14901133, -0.03241901],
        [-0.03241901,  0.95484861]],

       [[ 0.63480459,  0.72971575],
        [ 0.72971575,  1.16110086]]])

In [80]:
gm_model.converged_, gm_model.n_iter_

(True, 4)

In [81]:
gm_model.bic(X), gm_model.aic(X)

(8189.756836104972, 8102.531555989934)

## Evaluate <ins>gaussian mixture</ins> model

In [82]:
gm_model.predict(X)

array([0, 0, 2, ..., 1, 1, 1])

In [83]:
gm_model.predict_proba(X)

array([[9.76688618e-01, 2.33107018e-02, 6.80230786e-07],
       [9.82774531e-01, 1.65481663e-02, 6.77302883e-04],
       [7.42085667e-05, 2.04358925e-06, 9.99923748e-01],
       ...,
       [4.21582331e-07, 9.99999578e-01, 2.17682412e-26],
       [4.93027253e-16, 1.00000000e+00, 1.50345348e-41],
       [2.19825399e-15, 1.00000000e+00, 8.24833927e-41]])

In [84]:
gm_model.score_samples(X)

array([-2.60753797, -3.57117632, -3.32962239, ..., -3.51337454,
       -4.39800533, -3.80760349])

## Sample <ins>gaussian mixture</ins> model

In [85]:
X_new, y_new = gm_model.sample(6)

In [86]:
X_new, y_new

(array([[ 0.55895727,  0.63379664],
        [-1.17459034, -1.75364884],
        [ 4.02238918,  0.28158515],
        [ 3.88791592,  0.39278957],
        [-0.13443537,  2.55581224],
        [-0.96018408,  2.42388285]]),
 array([0, 0, 1, 1, 2, 2]))

## Anomaly detection <ins>gaussian mixture</ins> model

In [87]:
densities = gm_model.score_samples(X)

In [88]:
density_threshold = np.percentile(densities, 4)

In [89]:
anomalies = X[densities < density_threshold]
anomalies

array([[-0.11118987,  1.61334992],
       [ 0.62362922,  4.41540435],
       [ 1.49808977, -0.15251688],
       [ 0.74219223, -1.00445177],
       [-2.53940854, -2.76549965],
       [-1.62447969, -0.45770022],
       [-1.74680316, -0.78385111],
       [-3.58308316, -1.28249917],
       [ 0.53903026,  5.00244257],
       [-0.51480414, -2.16270124],
       [-1.81015204, -0.58926015],
       [-1.79651788, -0.97031471],
       [-2.11225785, -2.09712817],
       [-3.39408574, -2.28378778],
       [ 1.58082729,  4.20122873],
       [-2.48037945, -1.18651064],
       [-2.93972237, -1.41660564],
       [-1.62285961, -2.84860478],
       [-0.25954463, -1.7743691 ],
       [ 0.46018217,  2.78323717],
       [-2.06317379,  2.2670332 ],
       [ 0.13982849,  2.08023553],
       [-2.54004484, -2.8290338 ],
       [-1.93037427, -1.19447352],
       [-0.27124433, -1.86750177],
       [-1.15568262, -2.57480367],
       [-1.93315582,  2.49030105],
       [ 4.93207567, -0.42157602],
       [ 5.80546094,

## Train <ins>bayesian gaussian mixture</ins> model

In [90]:
bgm_model = BayesianGaussianMixture(n_components=10, n_init=10, random_state=RANDOM_SEED)

In [91]:
%%time
bgm_model.fit(X)

CPU times: user 3.64 s, sys: 1.69 s, total: 5.33 s
Wall time: 2.28 s


BayesianGaussianMixture(n_components=10, n_init=10, random_state=42)

In [92]:
bgm_model.weights_

array([3.95095317e-01, 2.05162685e-01, 3.99662331e-01, 7.24246329e-05,
       6.58404122e-06, 5.98549202e-07, 5.44135638e-08, 4.94668762e-09,
       4.49698874e-10, 4.08817159e-11])

In [93]:
bgm_model.means_

array([[ 0.06945986,  0.09573446],
       [ 3.42981808,  1.0391434 ],
       [-1.4021931 ,  1.42732498],
       [ 0.16952168,  0.82239288],
       [ 0.16952151,  0.82239288],
       [ 0.16952151,  0.82239288],
       [ 0.16952151,  0.82239288],
       [ 0.16952151,  0.82239288],
       [ 0.16952151,  0.82239288],
       [ 0.16952151,  0.82239288]])

In [94]:
bgm_model.covariances_

array([[[ 7.18174365e-01,  8.19657713e-01],
        [ 8.19657713e-01,  1.23961080e+00]],

       [[ 1.12952552e+00, -1.89441962e-03],
        [-1.89441962e-03,  9.35514115e-01]],

       [[ 6.49737954e-01,  7.29168497e-01],
        [ 7.29168497e-01,  1.16321806e+00]],

       [[ 1.97682967e+00,  2.04716652e-01],
        [ 2.04716652e-01,  7.57490145e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]],

       [[ 1.97682979e+00,  2.04716625e-01],
        [ 2.04716625e-01,  7.57490141e-01]]])

In [95]:
bgm_model.converged_, bgm_model.n_iter_

(True, 69)